-- =============================================================================
-- Hydria Database Schema (MySQL 8.0+)
-- Project: Hydria - Citizen Science Urban Water Quality Observation Platform
-- Engine: MySQL InnoDB (utf8mb4)
-- =============================================================================

CREATE DATABASE IF NOT EXISTS `hydria_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `hydria_db`;

-- -----------------------------------------------------------------------------
-- 1. USERS TABLE
-- Stores citizen science contributors, community monitors, and evaluators.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- 2. REPORTS TABLE
-- Stores citizen water body reports, GPS coordinates, sensory observations,
-- image metadata, workflow statuses, and Gemini AI analysis.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    water_body_name VARCHAR(255) NULL,
    water_body_type VARCHAR(100) NOT NULL,            -- 'Lake', 'River', 'Pond', 'Canal', 'Stream', 'Wetland', 'Other'
    latitude DECIMAL(10, 7) NOT NULL,                 -- GPS Latitude (-90.0 to 90.0)
    longitude DECIMAL(10, 7) NOT NULL,                -- GPS Longitude (-180.0 to 180.0)
    water_colour VARCHAR(100) NOT NULL,               -- 'Clear', 'Green', 'Dark Green', 'Brown', 'Yellowish', 'Black', 'Other'
    smell VARCHAR(100) NOT NULL,                      -- 'No smell', 'Musty / Earthy', 'Sewage-like smell', 'Chemical smell', 'Rotten eggs', 'Other'
    algae VARCHAR(100) NOT NULL,                      -- 'No', 'Mild / Surface scum', 'Moderate', 'Heavy / Dense bloom'
    visible_waste VARCHAR(100) NOT NULL,              -- 'None', 'Low', 'Moderate', 'High'
    water_appearance VARCHAR(100) NOT NULL,           -- 'Clean', 'Slightly Murky', 'Murky / Muddy', 'Very Dirty / Toxic'
    dead_fish VARCHAR(20) DEFAULT 'No',              -- 'No', 'Yes'
    additional_observation TEXT NULL,                 -- Free-text field notes
    image_path VARCHAR(500) NOT NULL,                 -- File storage path in uploads/
    image_hash VARCHAR(64) NOT NULL,                 -- 64-bit perceptual difference hash (dHash) for deduplication
    status ENUM('Not Watched', 'In Process', 'Submitted') NOT NULL DEFAULT 'Submitted',
    is_demo TINYINT(1) DEFAULT 0,                     -- 1 = demo record, 0 = citizen submission
    ai_analysis LONGTEXT NULL,                        -- Cached Google Gemini AI report analysis (JSON)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_reports_user_id (user_id),
    INDEX idx_reports_status (status),
    INDEX idx_reports_created_at (created_at),
    INDEX idx_reports_coords (latitude, longitude),
    INDEX idx_reports_image_hash (image_hash),
    CONSTRAINT fk_reports_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- 3. VOTES TABLE (Community Confirmation)
-- Implements "I observed this too" citizen science verification.
-- UNIQUE(user_id, report_id) enforces strictly one vote per user per report.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS votes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    report_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_user_report (user_id, report_id),
    INDEX idx_votes_report_id (report_id),
    CONSTRAINT fk_votes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_votes_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- 4. VALIDATIONS TABLE
-- Automated local validation logs generated by Hydria's Image & Report Engine.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS validations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    report_id INT NULL,
    file_valid TINYINT(1) DEFAULT 1,             -- 1 = valid format & size (< 5MB), 0 = invalid
    duplicate_check TINYINT(1) DEFAULT 1,        -- 1 = passed image perceptual hash check, 0 = duplicate detected
    image_suitability TINYINT(1) DEFAULT 1,      -- 1 = natural water palette detected, 0 = unsuitable
    location_check TINYINT(1) DEFAULT 1,         -- 1 = EXIF GPS matches or acceptable variance, 0 = mismatch
    missing_fields TEXT NULL,                    -- Comma-separated list of missing required attributes
    validation_message TEXT NULL,                -- Human-readable validation summary
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_validations_report_id (report_id),
    CONSTRAINT fk_validations_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- 5. DATABASE VIEWS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_community_reports AS
SELECT r.*, u.name AS submitter_name,
       (SELECT COUNT(*) FROM votes v WHERE v.report_id = r.id) AS vote_count
FROM reports r
JOIN users u ON r.user_id = u.id
WHERE r.status = 'Submitted'
ORDER BY r.created_at DESC;

CREATE OR REPLACE VIEW v_analysis_board AS
SELECT r.*, u.name AS submitter_name,
       (SELECT COUNT(*) FROM votes v WHERE v.report_id = r.id) AS vote_count
FROM reports r
JOIN users u ON r.user_id = u.id
ORDER BY r.created_at DESC;
